# Generated by Django 4.2.1 on 2024-05-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_nombreca_alter_producto_descipcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
