# Generated by Django 4.2.1 on 2024-05-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_foto_delete_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='ProyectoDonPepe/core/static/img'),
        ),
    ]
