# Generated by Django 4.2.1 on 2024-05-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='core/static/img/'),
        ),
    ]
