# Generated by Django 5.0.6 on 2024-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_itemcarrito_productocarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='nombreC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombreR',
            field=models.CharField(max_length=100),
        ),
    ]
