# Generated by Django 5.0.6 on 2024-06-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comuna_nombrec_alter_region_nombrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='status',
        ),
    ]
