# Generated by Django 5.0.6 on 2024-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_venta_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespacho',
            fields=[
                ('idDespacho', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreDespacho', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fEntrega',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fVenta',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codVenta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
