# Generated by Django 5.0.6 on 2024-06-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_estado_venta_tipodespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipodespacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodespacho'),
        ),
    ]
