# Generated by Django 5.0.6 on 2024-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_venta_tipodespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='idDireccion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
