# Generated by Django 5.0.6 on 2024-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_direccion_alter_venta_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='idDireccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
