# Generated by Django 5.0.6 on 2024-06-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_direccion_iddireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.direccion'),
        ),
    ]
