# Generated by Django 5.0.6 on 2024-06-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_venta_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direccion'),
        ),
    ]
