# Generated by Django 5.0.6 on 2024-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_venta_direccion_delete_direccionu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codVenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estadoP',
            field=models.IntegerField(default=1, verbose_name='Estado de la venta'),
        ),
    ]
