# Generated by Django 5.0.6 on 2024-06-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_direccion_venta_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='carrito',
        ),
    ]
