# Generated by Django 5.0.6 on 2024-06-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_venta_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estadoP',
            field=models.IntegerField(),
        ),
    ]
