# Generated by Django 5.0.6 on 2024-06-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_venta_estadop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estadoP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
